query fetchMenu($lang: LanguageCodeFilterEnum) {
  menuItems(where: { language: $lang, location: MENU_1, parentDatabaseId: 0 }) {
    nodes {
      id
      label
      uri
      childItems {
        nodes {
          id
          label
          uri
        }
      }
    }
  }
}
