query fetchPage($uri: ID!) {
  page(id: $uri, idType: URI) {
    id
    title
    content
    pageSidebarFields {
      theme
    }
    homepageFields {
      imageLanding {
        ...MediaItemFragment
      }
      imageFormations {
        ...MediaItemFragment
      }
      navigationFormations {
        __typename
        ... on Page {
          id
          title
          uri
        }
      }
      textCommandes
      imageCommandes {
        ...MediaItemFragment
      }
    }
    pageFields {
      sections {
        theme
        fullwidth
        flexiblecontent {
          type: __typename
          ... on Page_Pagefields_sections_Flexiblecontent_Title {
            title
          }
          ... on Page_Pagefields_sections_Flexiblecontent_Richtext {
            richtext
            twoColumns
          }
          ... on Page_Pagefields_sections_Flexiblecontent_Buttons {
            buttons {
              color
              link {
                target
                title
                url
              }
            }
          }
          ... on Page_Pagefields_sections_Flexiblecontent_Accordions {
            accordions {
              richtext
              title
            }
          }
          ... on Page_Pagefields_sections_Flexiblecontent_Slider {
            images {
              altText
              mediaDetails {
                sizes(include: GALLERY_VERTICAL) {
                  sourceUrl
                }
              }
            }
          }
          ... on Page_Pagefields_sections_Flexiblecontent_Testimonials {
            testimonials {
              text
              title
              image {
                ...MediaItemFragment
              }
            }
          }
          ... on Page_Pagefields_sections_Flexiblecontent_Galerie {
            fieldGroupName
            gallery {
              ... on Galerie {
                id
                slug
                title
                galleryFields {
                  gallery {
                    altText
                    mediaDetails {
                      sizes(include: GALLERY_VERTICAL) {
                        sourceUrl
                      }
                    }
                  }
                }
              }
            }
          }
          ... on Page_Pagefields_sections_Flexiblecontent_Video {
            fieldGroupName
            video
          }
          ... on Page_Pagefields_sections_Flexiblecontent_Agenda {
            fieldGroupName
            event {
              date
              fieldGroupName
              richtext
            }
          }
        }
      }
    }
    translations {
      id
      uri
      language {
        id
        code
        locale
      }
    }
  }
}

fragment MediaItemFragment on MediaItem {
  id
  altText
  mediaDetails {
    sizes(include: THUMBNAIL) {
      sourceUrl
    }
  }
}
