query fetchMenu($lang: LanguageCodeFilterEnum, $location: MenuLocationEnum) {
  menuItems(
    where: { language: $lang, location: $location, parentDatabaseId: 0 }
  ) {
    nodes {
      id
      label
      uri
      childItems {
        nodes {
          id
          label
          uri
        }
      }
    }
  }
}
