query fetchPage($uri: ID!) {
  page(id: $uri, idType: URI) {
    id
    title
    content
    pageFields {
      sections {
        theme
        flexiblecontent {
          type: __typename
          ... on Page_Pagefields_sections_Flexiblecontent_Title {
            title
          }
          ... on Page_Pagefields_sections_Flexiblecontent_Richtext {
            richtext
          }
          ... on Page_Pagefields_sections_Flexiblecontent_Buttons {
            buttons {
              color
              link {
                target
                title
                url
              }
            }
          }
          ... on Page_Pagefields_sections_Flexiblecontent_Accordions {
            accordions {
              richtext
              title
            }
          }
          ... on Page_Pagefields_sections_Flexiblecontent_Slider {
            images {
              altText
              mediaDetails {
                sizes(include: GALLERY_VERTICAL) {
                  sourceUrl
                }
              }
            }
          }
          ... on Page_Pagefields_sections_Flexiblecontent_Testimonials {
            testimonials {
              text
              title
              image {
                altText
                mediaDetails {
                  sizes(include: THUMBNAIL) {
                    sourceUrl
                  }
                }
              }
            }
          }
        }
      }
    }
    translations {
      id
      uri
      language {
        id
        code
        locale
      }
    }
  }
}
