query fetchMenu($lang: LanguageCodeFilterEnum, $location: MenuLocationEnum) {
  menuItems(
    where: { language: $lang, location: $location, parentDatabaseId: 0 }
  ) {
    nodes {
      label
      uri
      cssClasses
      childItems {
        nodes {
          label
          uri
          cssClasses
        }
      }
    }
  }
}
