name: Deploy backend

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-backend.yml
      - wordpress/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wordpress

    steps:
      - uses: actions/checkout@v3

      # - name: Cache Composer dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: /tmp/composer-cache
      #     key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: '7.4'
          args: '--working-dir=./wordpress'

      - name: 🔗 Creates symlink
        run: |
          ln -s /home/jminguely/www/api.ecolecouture.ch/shared/web/app/uploads ./web/app/uploads
          ln -s /home/jminguely/www/api.ecolecouture.ch/shared/web/.htaccess ./web/.htaccess
          ln -s /home/jminguely/www/api.ecolecouture.ch/shared/.env ./.env

      - name: 🚀 Ship the whole thin
        id: deploy
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: '-avzrl --delete'
          options: ''
          ssh_options: ''
          src: './wordpress'
          dest: ${{vars.DEPLOY_DEST}}
