name: Deploy backend

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-backend.yml
      - wordpress/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./worpress

    steps:
      - uses: actions/checkout@v3

      - name: 🔗 Creates symlink
        run: |
          ln -s /api.ecolecouture.ch/shared/web/app/uploads ./wordpress/web/app/uploads
          ln -s /api.ecolecouture.ch/shared/web/.htaccess ./wordpress/web/.htaccess
          ln -s /api.ecolecouture.ch/shared/.env ./wordpress/.env

      - name: 🚀 Ship the whole thin
        id: deploy
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: '-avzrl --delete'
          options: ''
          ssh_options: '-p 2121'
          src: './wordpress'
          dest: ${{vars.DEPLOY_DEST}}
